-- =====================================================================
-- SCHEMA DATABASE & STORAGE CMS CV KARYA PUTRA NUSANTARA (KPN)
-- =====================================================================
-- Jalankan skrip ini di SQL Editor pada Supabase Dashboard Anda.
-- URL: https://qqnghnacaitjewsgdtda.supabase.co

-- 1. TABEL PORTFOLIO
CREATE TABLE IF NOT EXISTS public.portfolio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    year TEXT NOT NULL,
    description TEXT NOT NULL,
    image TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABEL INSIGHTS / BERITA
CREATE TABLE IF NOT EXISTS public.insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    date TEXT NOT NULL,
    excerpt TEXT NOT NULL,
    content TEXT,
    image TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABEL CLIENTS / PARTNER
CREATE TABLE IF NOT EXISTS public.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    logo TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABEL SERVICES / LAYANAN
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    tag TEXT NOT NULL,
    short_desc TEXT NOT NULL,
    description TEXT NOT NULL,
    image TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABEL PRODUCTS / SOLUTIONS
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    image TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABEL CONTACT SETTINGS
CREATE TABLE IF NOT EXISTS public.contact_settings (
    id INT PRIMARY KEY DEFAULT 1,
    phone TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    email TEXT NOT NULL,
    instagram TEXT NOT NULL,
    facebook TEXT NOT NULL,
    address TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. TABEL SITE COPY (Konten Utama Website)
CREATE TABLE IF NOT EXISTS public.site_copy (
    id INT PRIMARY KEY DEFAULT 1,
    hero_image TEXT NOT NULL,
    about_image TEXT NOT NULL,
    hero_eyebrow TEXT NOT NULL,
    hero_title TEXT NOT NULL,
    hero_desc TEXT NOT NULL,
    about_title TEXT NOT NULL,
    about_text1 TEXT NOT NULL,
    about_text2 TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================================
ALTER TABLE public.portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_copy ENABLE ROW LEVEL SECURITY;

-- Kebijakan Akses: Publik dapat Membaca (SELECT)
CREATE POLICY "Public Read Portfolio" ON public.portfolio FOR SELECT USING (true);
CREATE POLICY "Public Read Insights" ON public.insights FOR SELECT USING (true);
CREATE POLICY "Public Read Clients" ON public.clients FOR SELECT USING (true);
CREATE POLICY "Public Read Services" ON public.services FOR SELECT USING (true);
CREATE POLICY "Public Read Products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Public Read Contact" ON public.contact_settings FOR SELECT USING (true);
CREATE POLICY "Public Read SiteCopy" ON public.site_copy FOR SELECT USING (true);

-- Kebijakan Akses: Admin / Client dapat Melakukan CRUD (ALL)
CREATE POLICY "Admin CRUD Portfolio" ON public.portfolio FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin CRUD Insights" ON public.insights FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin CRUD Clients" ON public.clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin CRUD Services" ON public.services FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin CRUD Products" ON public.products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin CRUD Contact" ON public.contact_settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin CRUD SiteCopy" ON public.site_copy FOR ALL USING (true) WITH CHECK (true);

-- =====================================================================
-- STORAGE BUCKET: kpn-assets
-- =====================================================================
INSERT INTO storage.buckets (id, name, public) 
VALUES ('kpn-assets', 'kpn-assets', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Access Storage" ON storage.objects FOR SELECT USING (bucket_id = 'kpn-assets');
CREATE POLICY "Admin Storage Insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'kpn-assets');
CREATE POLICY "Admin Storage Update" ON storage.objects FOR UPDATE USING (bucket_id = 'kpn-assets');
CREATE POLICY "Admin Storage Delete" ON storage.objects FOR DELETE USING (bucket_id = 'kpn-assets');

-- =====================================================================
-- SEED DATA AWAL KPN (PRESERVE ALL EXISTING CONTENT)
-- =====================================================================
INSERT INTO public.contact_settings (id, phone, whatsapp, email, instagram, facebook, address)
VALUES (
    1,
    '082249501188',
    'https://wa.me/6282249501188',
    'cv.kpn2019@gnail.com',
    'https://www.instagram.com/videotronmurahsurabaya?igsi=MWNwamRwMm9kMnh6Zg==',
    'https://www.facebook.com/share/1DRjddx7jz/',
    'Jl. Permata Sukodono Raya No.01 Cluster Beryl Blok H1, Sukodono, Sukodono, Kec. Sukodono, Kabupaten Sidoarjo, Jawa Timur 61258'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.site_copy (id, hero_image, about_image, hero_eyebrow, hero_title, hero_desc, about_title, about_text1, about_text2)
VALUES (
    1,
    '/images/01-HERO-ganti-dengan-foto-proyek-utama.jpg',
    '/images/02-TENTANG-ganti-dengan-foto-kantor-atau-tim.jpg',
    'General Trading • Distributor • Supplier • Contractor',
    'Partner Pengadaan Untuk Kebutuhan Bisnis Anda.',
    'Karya Putra Nusantara hadir sebagai partner pengadaan barang dan solusi proyek yang mengutamakan kualitas, ketepatan, dan pelayanan profesional.',
    'Lebih dari sekadar supplier.',
    'CV Karya Putra Nusantara berdiri sebagai perusahaan General Trading, Distributor, Supplier, General Contractor, dan Business Consultant.',
    'Kami membantu kebutuhan pengadaan barang dan solusi proyek melalui pendekatan yang fleksibel—dari kebutuhan produk, konsultasi, pengadaan, hingga implementasi.'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.services (id, title, tag, short_desc, description, image) VALUES
(1, 'Videotron & Digital Display', 'DISPLAY', 'LED display untuk branding, informasi, promosi, dan komunikasi visual.', 'Solusi LED display untuk kebutuhan informasi, promosi, ruang publik, corporate communication, hingga kebutuhan project outdoor maupun indoor.', '/images/03-LAYANAN-videotron.jpg'),
(2, 'Interactive Display', 'INTERACTIVE', 'Interactive TV, smart display, dan perangkat presentasi.', 'Interactive TV, smart display, dan perangkat presentasi untuk ruang meeting, pendidikan, auditorium, command center, dan kebutuhan kolaborasi.', '/images/04-LAYANAN-interactive-display.jpg'),
(3, 'Lighting & Electrical', 'ELECTRICAL', 'Lighting, PJU, industrial lighting, dan kebutuhan kelistrikan.', 'Pengadaan lighting, PJU, industrial lighting, panel, komponen, dan kebutuhan kelistrikan untuk fasilitas serta berbagai proyek.', '/images/05-LAYANAN-lighting-dan-electrical.jpg'),
(4, 'IT Support & Security System', 'IT & SECURITY', 'CCTV, access control, networking, dan perangkat IT.', 'CCTV, access control, networking, perangkat IT, dan dukungan sistem untuk kebutuhan keamanan serta operasional bisnis.', '/images/06-LAYANAN-it-dan-security.jpeg'),
(5, 'Solar Cell & Energy Solution', 'ENERGY', 'Solusi energi berbasis solar untuk fasilitas dan proyek.', 'Solusi energi berbasis solar cell untuk fasilitas, project site, kebutuhan efisiensi energi, dan pengembangan infrastruktur.', '/images/07-LAYANAN-solar-cell.jpeg'),
(6, 'Manufacturing & Infrastructure', 'PROJECT', 'Pengadaan dan kebutuhan pendukung proyek serta infrastruktur.', 'Pengadaan dan pekerjaan pendukung konstruksi, manufacturing, facility, serta kebutuhan infrastruktur sesuai kebutuhan proyek.', '/images/08-LAYANAN-manufacturing-infrastructure.jpg')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.portfolio (id, title, category, year, description, image) VALUES
(1, 'Pertamina Asset 4 – Surabaya', 'Videotron', '2025', 'Pengadaan & instalasi videotron untuk kebutuhan komunikasi visual dan project facility.', '/images/01-HERO-ganti-dengan-foto-proyek-utama.jpg'),
(2, 'KPU Provinsi Jawa Timur – Surabaya', 'Digital Display', '2025', 'Instalasi display digital untuk mendukung kebutuhan informasi dan komunikasi publik.', '/images/10-PROJECT-KPU-Jawa-Timur.jpg'),
(3, 'Dinas Kominfo – Pasuruan', 'Videotron Outdoor', '2025', 'Pengadaan videotron outdoor untuk kebutuhan informasi publik dan komunikasi visual.', '/images/11-PROJECT-Kominfo-Pasuruan.jpg'),
(4, 'PPSDM Migas – Cepu', 'Interactive Display', '2025', 'Fasilitas smart display auditorium untuk kebutuhan presentasi dan pembelajaran.', '/images/12-PROJECT-PPSDM-Migas-Cepu.jpg'),
(5, 'Bank BNI Graha Pangeran – Surabaya', 'Digital Signage', '2025', 'Digital signage & display untuk mendukung komunikasi visual di area fasilitas.', '/images/13-PROJECT-BNI-Graha-Pangeran.jpg'),
(6, 'Telkomsel – Jakarta', 'Display & IT', '2025', 'Display dan dukungan IT untuk kebutuhan ruang dan project operasional.', '/images/14-PROJECT-Telkomsel-Jakarta.jpg'),
(7, 'RS Kemenkes – Makassar', 'Information Display', '2025', 'Display informasi untuk mendukung kebutuhan komunikasi dan layanan fasilitas.', '/images/15-PROJECT-RS-Kemenkes-Makassar.jpg'),
(8, 'MAN 1 Gresik', 'Smart Classroom', '2025', 'Smart classroom dan LED screen untuk kebutuhan pembelajaran dan presentasi.', '/images/16-PROJECT-MAN-1-Gresik.jpg')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.insights (id, title, category, date, excerpt, content, image) VALUES
(1, 'Panduan Memilih Videotron untuk Kebutuhan Bisnis', 'Edukasi', '05 Sep 2026', 'Ukuran, brightness, pixel pitch, lokasi pemasangan, dan kebutuhan konten perlu disesuaikan sejak awal.', 'Panduan lengkap memilih videotron untuk kebutuhan bisnis indoor maupun outdoor.', '/images/17-BERITA-videotron.jpg'),
(2, 'Pengadaan Barang yang Rapi Dimulai dari Kebutuhan yang Jelas', 'Procurement', '02 Sep 2026', 'Pengadaan yang tepat bukan sekadar mencari harga, tetapi memastikan spesifikasi, kualitas, waktu, dan implementasi sesuai kebutuhan.', 'Tips melakukan pengadaan barang yang terencana dan efisien.', '/images/18-BERITA-pengadaan.jpg'),
(3, 'Digital Display untuk Ruang Publik dan Area Bisnis', 'Insight', '28 Agu 2026', 'Display digital dapat dipakai untuk informasi, branding, navigasi, promosi, hingga komunikasi internal.', 'Manfaat digital display untuk instansi pemerintah dan gedung komersial.', '/images/19-BERITA-digital-display.jpg')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.clients (id, name, logo) VALUES
(1, 'Pertamina', '/images/pertamina.jpg'),
(2, 'KPU Jawa Timur', '/images/10-PROJECT-KPU-Jawa-Timur.jpg'),
(3, 'Kominfo', '/images/11-PROJECT-Kominfo-Pasuruan.jpg'),
(4, 'PPSDM Migas', '/images/12-PROJECT-PPSDM-Migas-Cepu.jpg'),
(5, 'BNI', '/images/13-PROJECT-BNI-Graha-Pangeran.jpg'),
(6, 'Telkomsel', '/images/14-PROJECT-Telkomsel-Jakarta.jpg'),
(7, 'Kemenkes', '/images/15-PROJECT-RS-Kemenkes-Makassar.jpg'),
(8, 'MAN 1 Gresik', '/images/16-PROJECT-MAN-1-Gresik.jpg')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.products (id, title, category, description, image) VALUES
(1, 'Outdoor Videotron P3.9', 'Videotron', 'High brightness outdoor LED display anti air untuk promosi dan iklan publik.', '/images/03-LAYANAN-videotron.jpg'),
(2, 'Interactive Smartboard 75 inch', 'Display', 'Smart interactive whiteboard 4K untuk ruang meeting modern dan smart classroom.', '/images/04-LAYANAN-interactive-display.jpg')
ON CONFLICT (id) DO NOTHING;
